import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import HeroSection from '../components/HeroSection'
import Navbar from '../components/Navbar'
import CardsContainer from '../containers/CardsContainer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Navbar />
        <HeroSection text="Cadence is Magic and FCL it's your wand! Learn to cast your spells and become the next mage developer inside the Flow ecosystem.      Cadence is Magic and FCL it's your wand! Learn to cast your spells and become the next mage developer inside the Flow ecosystem."/>
        <CardsContainer />
      </Wrapper>
    </>
  )
}

const Wrapper = styled.main`
  width: 100%;
  height: 100%;
  min-height: 100vh;
  background-image: url("./bgMagicSchool.png");
  overflow: hidden;
`
