import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
// useRouter 
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Flow Magic Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        {/* <Navbar /> */}
        <header>
          <div>
            <Image src="/assets/logo.png" alt="logo" height={100} width={100} />
          </div>
          <div className="slogan">
            <p>OUR PROFESSORS ARE WAITING FOR YOU</p>
            <span>START NOW YOUR JOURNEY</span>
          </div>
        </header>
        <section className="actions">
          <button onClick={() => router.push("/viewSamplers")}>SEE SAMPLERS</button>

          <button>START GAME</button>
        </section>
        <div className="hero-img">
          <Image src="/assets/heroImg.png" alt="img" layout="fill" />
        </div>
      </Wrapper>
    </>
  );
}

const Wrapper = styled.main`
  width: 100%;
  height: 100vh;
  font-family: "Michroma", sans-serif;
  min-height: 100vh;
  background: linear-gradient(180deg, #6100ff -47.66%, #000000 100%);
  overflow: hidden;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;

  p{
    font-size: 1.5rem;
  }

  header {
    height: 36%;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    text-align: center;
    color:white;
  }

  .slogan {
    margin-top: 2rem;
  }

  button {
    background: #00ffb2;
    width: 15rem;
    height: 4rem;
    border-radius: 0.5rem;
    margin: 0.5rem 0rem;
    cursor: pointer;
    z-index:99;
  }

  .hero-img {
    position: absolute;
    bottom: 0;
    height: 60%;
    width: 100%;
  }

  .actions {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    height: 70%;
  }
`;
